import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-bc-color',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bc-color.component.html',
  styleUrl: './bc-color.component.css',
})
export class BcColorComponent {
  backgroundColors = [
    {
      shades: [
        { class: 'bg-blue-100', label: 'bg-blue-100' },
        { class: 'bg-blue-200', label: 'bg-blue-200' },
        { class: 'bg-blue-300', label: 'bg-blue-300' },
        { class: 'bg-blue-400', label: 'bg-blue-400' },
        { class: 'bg-blue-500', label: 'bg-blue-500' },
        { class: 'bg-blue-600', label: 'bg-blue-600' },
        { class: 'bg-blue-700', label: 'bg-blue-700' },
        { class: 'bg-blue-800', label: 'bg-blue-800' },
        { class: 'bg-blue-900', label: 'bg-blue-900' },
        { class: 'bg-indigo-100', label: 'bg-indigo-100' },
        { class: 'bg-indigo-200', label: 'bg-indigo-200' },
        { class: 'bg-indigo-300', label: 'bg-indigo-300' },
        { class: 'bg-indigo-400', label: 'bg-indigo-400' },
        { class: 'bg-indigo-500', label: 'bg-indigo-500' },
        { class: 'bg-indigo-600', label: 'bg-indigo-600' },
        { class: 'bg-indigo-700', label: 'bg-indigo-700' },
        { class: 'bg-indigo-800', label: 'bg-indigo-800' },
        { class: 'bg-indigo-900', label: 'bg-indigo-900' },
        { class: 'bg-purple-100', label: 'bg-purple-100' },
        { class: 'bg-purple-200', label: 'bg-purple-200' },
        { class: 'bg-purple-300', label: 'bg-purple-300' },
        { class: 'bg-purple-400', label: 'bg-purple-400' },
        { class: 'bg-purple-500', label: 'bg-purple-500' },
        { class: 'bg-purple-600', label: 'bg-purple-600' },
        { class: 'bg-purple-700', label: 'bg-purple-700' },
        { class: 'bg-purple-800', label: 'bg-purple-800' },
        { class: 'bg-purple-900', label: 'bg-purple-900' },
        { class: 'bg-pink-100', label: 'bg-pink-100' },
        { class: 'bg-pink-200', label: 'bg-pink-200' },
        { class: 'bg-pink-300', label: 'bg-pink-300' },
        { class: 'bg-pink-400', label: 'bg-pink-400' },
        { class: 'bg-pink-500', label: 'bg-pink-500' },
        { class: 'bg-pink-600', label: 'bg-pink-600' },
        { class: 'bg-pink-700', label: 'bg-pink-700' },
        { class: 'bg-pink-800', label: 'bg-pink-800' },
        { class: 'bg-pink-900', label: 'bg-pink-900' },
        { class: 'bg-red-100', label: 'bg-red-100' },
        { class: 'bg-red-200', label: 'bg-red-200' },
        { class: 'bg-red-300', label: 'bg-red-300' },
        { class: 'bg-red-400', label: 'bg-red-400' },
        { class: 'bg-red-500', label: 'bg-red-500' },
        { class: 'bg-red-600', label: 'bg-red-600' },
        { class: 'bg-red-700', label: 'bg-red-700' },
        { class: 'bg-red-800', label: 'bg-red-800' },
        { class: 'bg-red-900', label: 'bg-red-900' },
        { class: 'bg-orange-100', label: 'bg-orange-100' },
        { class: 'bg-orange-200', label: 'bg-orange-200' },
        { class: 'bg-orange-300', label: 'bg-orange-300' },
        { class: 'bg-orange-400', label: 'bg-orange-400' },
        { class: 'bg-orange-500', label: 'bg-orange-500' },
        { class: 'bg-orange-600', label: 'bg-orange-600' },
        { class: 'bg-orange-700', label: 'bg-orange-700' },
        { class: 'bg-orange-800', label: 'bg-orange-800' },
        { class: 'bg-orange-900', label: 'bg-orange-900' },
        { class: 'bg-yellow-100', label: 'bg-yellow-100' },
        { class: 'bg-yellow-200', label: 'bg-yellow-200' },
        { class: 'bg-yellow-300', label: 'bg-yellow-300' },
        { class: 'bg-yellow-400', label: 'bg-yellow-400' },
        { class: 'bg-yellow-500', label: 'bg-yellow-500' },
        { class: 'bg-yellow-600', label: 'bg-yellow-600' },
        { class: 'bg-yellow-700', label: 'bg-yellow-700' },
        { class: 'bg-yellow-800', label: 'bg-yellow-800' },
        { class: 'bg-yellow-900', label: 'bg-yellow-900' },
        { class: 'bg-green-100', label: 'bg-green-100' },
        { class: 'bg-green-200', label: 'bg-green-200' },
        { class: 'bg-green-300', label: 'bg-green-300' },
        { class: 'bg-green-400', label: 'bg-green-400' },
        { class: 'bg-green-500', label: 'bg-green-500' },
        { class: 'bg-green-600', label: 'bg-green-600' },
        { class: 'bg-green-700', label: 'bg-green-700' },
        { class: 'bg-green-800', label: 'bg-green-800' },
        { class: 'bg-green-900', label: 'bg-green-900' },
        { class: 'bg-teal-100', label: 'bg-teal-100' },
        { class: 'bg-teal-200', label: 'bg-teal-200' },
        { class: 'bg-teal-300', label: 'bg-teal-300' },
        { class: 'bg-teal-400', label: 'bg-teal-400' },
        { class: 'bg-teal-500', label: 'bg-teal-500' },
        { class: 'bg-teal-600', label: 'bg-teal-600' },
        { class: 'bg-teal-700', label: 'bg-teal-700' },
        { class: 'bg-teal-800', label: 'bg-teal-800' },
        { class: 'bg-teal-900', label: 'bg-teal-900' },
        { class: 'bg-cyan-100', label: 'bg-cyan-100' },
        { class: 'bg-cyan-200', label: 'bg-cyan-200' },
        { class: 'bg-cyan-300', label: 'bg-cyan-300' },
        { class: 'bg-cyan-400', label: 'bg-cyan-400' },
        { class: 'bg-cyan-500', label: 'bg-cyan-500' },
        { class: 'bg-cyan-600', label: 'bg-cyan-600' },
        { class: 'bg-cyan-700', label: 'bg-cyan-700' },
        { class: 'bg-cyan-800', label: 'bg-cyan-800' },
        { class: 'bg-cyan-900', label: 'bg-cyan-900' },
        { class: 'bg-gray-100', label: 'bg-gray-100' },
        { class: 'bg-gray-200', label: 'bg-gray-200' },
        { class: 'bg-gray-300', label: 'bg-gray-300' },
        { class: 'bg-gray-400', label: 'bg-gray-400' },
        { class: 'bg-gray-500', label: 'bg-gray-500' },
        { class: 'bg-gray-600', label: 'bg-gray-600' },
        { class: 'bg-gray-700', label: 'bg-gray-700' },
        { class: 'bg-gray-800', label: 'bg-gray-800' },
        { class: 'bg-gray-900', label: 'bg-gray-900' },
      ],
    },
    // Add more color categories...
  ];

  textColors = [
    {
      shades: [
        { class: 'text-blue-100', label: 'text-blue-100' },
        { class: 'text-blue-200', label: 'text-blue-200' },
        { class: 'text-blue-300', label: 'text-blue-300' },
        { class: 'text-blue-400', label: 'text-blue-400' },
        { class: 'text-blue-500', label: 'text-blue-500' },
        { class: 'text-blue-600', label: 'text-blue-600' },
        { class: 'text-blue-700', label: 'text-blue-700' },
        { class: 'text-blue-800', label: 'text-blue-800' },
        { class: 'text-blue-900', label: 'text-blue-900' },
        { class: 'text-indigo-100', label: 'text-indigo-100' },
        { class: 'text-indigo-200', label: 'text-indigo-200' },
        { class: 'text-indigo-300', label: 'text-indigo-300' },
        { class: 'text-indigo-400', label: 'text-indigo-400' },
        { class: 'text-indigo-500', label: 'text-indigo-500' },
        { class: 'text-indigo-600', label: 'text-indigo-600' },
        { class: 'text-indigo-700', label: 'text-indigo-700' },
        { class: 'text-indigo-800', label: 'text-indigo-800' },
        { class: 'text-indigo-900', label: 'text-indigo-900' },
        { class: 'text-purple-100', label: 'text-purple-100' },
        { class: 'text-purple-200', label: 'text-purple-200' },
        { class: 'text-purple-300', label: 'text-purple-300' },
        { class: 'text-purple-400', label: 'text-purple-400' },
        { class: 'text-purple-500', label: 'text-purple-500' },
        { class: 'text-purple-600', label: 'text-purple-600' },
        { class: 'text-purple-700', label: 'text-purple-700' },
        { class: 'text-purple-800', label: 'text-purple-800' },
        { class: 'text-purple-900', label: 'text-purple-900' },
        { class: 'text-pink-100', label: 'text-pink-100' },
        { class: 'text-pink-200', label: 'text-pink-200' },
        { class: 'text-pink-300', label: 'text-pink-300' },
        { class: 'text-pink-400', label: 'text-pink-400' },
        { class: 'text-pink-500', label: 'text-pink-500' },
        { class: 'text-pink-600', label: 'text-pink-600' },
        { class: 'text-pink-700', label: 'text-pink-700' },
        { class: 'text-pink-800', label: 'text-pink-800' },
        { class: 'text-pink-900', label: 'text-pink-900' },
        { class: 'text-red-100', label: 'text-red-100' },
        { class: 'text-red-200', label: 'text-red-200' },
        { class: 'text-red-300', label: 'text-red-300' },
        { class: 'text-red-400', label: 'text-red-400' },
        { class: 'text-red-500', label: 'text-red-500' },
        { class: 'text-red-600', label: 'text-red-600' },
        { class: 'text-red-700', label: 'text-red-700' },
        { class: 'text-red-800', label: 'text-red-800' },
        { class: 'text-red-900', label: 'text-red-900' },
        { class: 'text-orange-100', label: 'text-orange-100' },
        { class: 'text-orange-200', label: 'text-orange-200' },
        { class: 'text-orange-300', label: 'text-orange-300' },
        { class: 'text-orange-400', label: 'text-orange-400' },
        { class: 'text-orange-500', label: 'text-orange-500' },
        { class: 'text-orange-600', label: 'text-orange-600' },
        { class: 'text-orange-700', label: 'text-orange-700' },
        { class: 'text-orange-800', label: 'text-orange-800' },
        { class: 'text-orange-900', label: 'text-orange-900' },
        { class: 'text-yellow-100', label: 'text-yellow-100' },
        { class: 'text-yellow-200', label: 'text-yellow-200' },
        { class: 'text-yellow-300', label: 'text-yellow-300' },
        { class: 'text-yellow-400', label: 'text-yellow-400' },
        { class: 'text-yellow-500', label: 'text-yellow-500' },
        { class: 'text-yellow-600', label: 'text-yellow-600' },
        { class: 'text-yellow-700', label: 'text-yellow-700' },
        { class: 'text-yellow-800', label: 'text-yellow-800' },
        { class: 'text-yellow-900', label: 'text-yellow-900' },
        { class: 'text-green-100', label: 'text-green-100' },
        { class: 'text-green-200', label: 'text-green-200' },
        { class: 'text-green-300', label: 'text-green-300' },
        { class: 'text-green-400', label: 'text-green-400' },
        { class: 'text-green-500', label: 'text-green-500' },
        { class: 'text-green-600', label: 'text-green-600' },
        { class: 'text-green-700', label: 'text-green-700' },
        { class: 'text-green-800', label: 'text-green-800' },
        { class: 'text-green-900', label: 'text-green-900' },
        { class: 'text-teal-100', label: 'text-teal-100' },
        { class: 'text-teal-200', label: 'text-teal-200' },
        { class: 'text-teal-300', label: 'text-teal-300' },
        { class: 'text-teal-400', label: 'text-teal-400' },
        { class: 'text-teal-500', label: 'text-teal-500' },
        { class: 'text-teal-600', label: 'text-teal-600' },
        { class: 'text-teal-700', label: 'text-teal-700' },
        { class: 'text-teal-800', label: 'text-teal-800' },
        { class: 'text-teal-900', label: 'text-teal-900' },
        { class: 'text-cyan-100', label: 'text-cyan-100' },
        { class: 'text-cyan-200', label: 'text-cyan-200' },
        { class: 'text-cyan-300', label: 'text-cyan-300' },
        { class: 'text-cyan-400', label: 'text-cyan-400' },
        { class: 'text-cyan-500', label: 'text-cyan-500' },
        { class: 'text-cyan-600', label: 'text-cyan-600' },
        { class: 'text-cyan-700', label: 'text-cyan-700' },
        { class: 'text-cyan-800', label: 'text-cyan-800' },
        { class: 'text-cyan-900', label: 'text-cyan-900' },
        { class: 'text-gray-100', label: 'text-gray-100' },
        { class: 'text-gray-200', label: 'text-gray-200' },
        { class: 'text-gray-300', label: 'text-gray-300' },
        { class: 'text-gray-400', label: 'text-gray-400' },
        { class: 'text-gray-500', label: 'text-gray-500' },
        { class: 'text-gray-600', label: 'text-gray-600' },
        { class: 'text-gray-700', label: 'text-gray-700' },
        { class: 'text-gray-800', label: 'text-gray-800' },
        { class: 'text-gray-900', label: 'text-gray-900' },
      ],
    },
    // Add more color categories...
  ];
}
